[documents]
    git_stop_words = "op://yc7nim47s6rch4ehrvfsz5icei/vgapmuu57fs3ic44wyupk2orgi/notesPlain"

[secrets]
    bws_zoom_address = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/bws_zoom_link"
    calendly_address = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/calendly"
    email_address    = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/default_email"
    gitea_address    = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/gitea_url"
    zoom_address     = "op://yc7nim47s6rch4ehrvfsz5icei/cq4if4oayozhsfhleijuw6n2aa/zoom_link"
